### ISSUE TITLE
panic upon trying to calculate with negative numbers

### ISSUE THREAD

**Issue by Mystikfluu** [Alpisc/Rust-Calculator#1]
## What's the error
Upon entering the command `1^-2` (or any negative exponent) you get the following error:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\calculator.rs:138:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\Calculator.exe` (exit code: 101)
```

### Proposed solution
Tell the user the operation can not be done in the calculator, or implement handling negative numbers

**Comment by Alpisc** [comment]
since this is a internal rust function, i will not be able to fix this issue, however if you were to come up with a solution your self, dont hesitate to make it a pull request. I will gladly intigrate it.

**Comment by Mystikfluu** [comment]
after checking some stuff, the error actually lies in the fact that negative numbers are currently not supported (if not done by subtraction)
